### ISSUE TITLE
UI - Capture Discord UserId in Client table/page

### ISSUE THREAD

**Issue by The1CABAL** [The1CABAL/SkaldBot#53]
The user needs the option of entering in their discord Id to receive the announcements sent by changes in #52

**Comment by DevinWalkup** [comment]
Should this be tracked in the Accounts table or the Users table?

**Comment by The1CABAL** [comment]
Users. I think it will be rare that an account has multiple users but just in case, the announcement should be able to go to all users

**Comment by DevinWalkup** [comment]
On the registration form and the add user form (when the user creation form gets created for the account profile) we will need to provide a link to the discord documentation on how the user can get their User Id.

Once #62 is finished, implement this functionality for the documentation instead of directly linking to discord documentation.
